### ISSUE TITLE
Add a button to copy received/sent telegram to clipboard

### ISSUE THREAD

**Issue by rudyxp** [dominik-tylczynski/mfs-plc-sim#18]
For emulator GUI, I need to copy and paste multiple times for a single telegram. Is it possible to add a button to export them into the clipboard.
Something like below, click the button and export the full telegram.
![image](https://github.com/dominik-tylczynski/mfs-plc-sim/assets/55109055/4f190801-33e2-4c0b-9b6a-436f136e630a)

**Comment by dominik-tylczynski** [comment]
Thank our for your comment. I'll put that as a feature request and will implement that in my spare time. In the meantime, you can copy telegrams from the main window.

**Comment by dominik-tylczynski** [comment]
Delivered with release 20240813
