### ISSUE TITLE
High CPU utiliazation running the SIM on Windows

### ISSUE THREAD

**Issue by PatrickRogge174** [dominik-tylczynski/mfs-plc-sim#8]
We are running the SIM on Windows.
First it was about 40% after pressing the start button at the SIM.
After a view days only having the SIM started it took 100% CPU without having the start button pressed. 

Environment:
Windows Server 2019 running as a virtual machine in Hyper V environment.

**Comment by dominik-tylczynski** [comment]
High CPU utilization observed after TCP/IP server is started in the _Sim_ class. Before that CPU utilization in negligible.
The problem is narrowed down to the _Telegram processor_ thread.

**Comment by dominik-tylczynski** [comment]
The issue is resolved. The new jar is generated.
